// <auto-generated />
using JackBotV2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JackBotV2.Migrations
{
    [DbContext(typeof(JackBotEntities))]
    [Migration("20210201185922_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("JackBotV2.Database.JackBotQuotes", b =>
                {
                    b.Property<string>("Quote")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Quote");

                    b.ToTable("JackBotQuotes");
                });
#pragma warning restore 612, 618
        }
    }
}
